version: "3"

services:

  redis:
    image: redis:5-alpine
    volumes:
      - redisdata:/data
    ports:
      - 6379:6379

  mosquitto:
    image: iegomez/sb-mosquitto-go-auth:0.5.0
    volumes:
      - ./conf:/etc/mosquitto
    ports:
      - 1883:1883

volumes:
  redisdata:
